# Configuration Checkov - PFE CloudSentinel
# Focus sur Terraform Azure et les bonnes pratiques de sécurité

directory:
  - .

soft-fail: false # En entreprise, on veut que le scan bloque si une erreur critique est trouvée

framework:
  - terraform

# On peut spécifier ici des patterns d'exclusion
skip-path:
  - 'node_modules'
  - '.terraform'

# On force la sortie en JSON pour faciliter l'intégration ultérieure
output:
  - cli
  - json

# Liste de contrôles à ignorer si nécessaire (par ID)
# skip-check:
#   - CKV_AZURE_33 # Exemple
