Mutelist:
  Accounts:
    "*":
      Checks:
        iam_role_user_access_admin_restricted:
          Regions:
            - "*"
          Resources:
            - "c90a27b7-049c-4eca-ab7d-aa1d1d85aff4"
            - "befee0f8-7c4e-451f-96a2-b3657cb58be6"
          Tags:
            - "*"
        storage_ensure_encryption_with_customer_managed_keys:
          Regions:
            - "*"
          Resources:
            - "*"
          Tags:
            - "*"
        storage_ensure_private_endpoints_in_storage_accounts:
          Regions:
            - "*"
          Resources:
            - "*"
          Tags:
            - "*"
        storage_geo_redundant_enabled:
          Regions:
            - "*"
          Resources:
            - "*"
          Tags:
            - "*"
        storage_smb_channel_encryption_with_secure_algorithm:
          Regions:
            - "*"
          Resources:
            - "*"
          Tags:
            - "*"
        storage_infrastructure_encryption_is_enabled:
          Regions:
            - "*"
          Resources:
            - "*"
          Tags:
            - "*"
        network_watcher_enabled:
          Regions:
            - "*"
          Resources:
            - "*"
          Tags:
            - "*"
        network_bastion_host_exists:
          Regions:
            - "*"
          Resources:
            - "*"
          Tags:
            - "*"
